### ISSUE TITLE
Does the cleanup impl make sense?

### ISSUE THREAD

**Issue by mattfbacon** [zekroTJA/timedmap-rs#1]
I see two main issues:

- Constant refetching of the time (implicit inside of `is_expired`)
- Does collecting into a `Vec` even make sense compared to a single `retain` call?

**Comment by zekroTJA** [comment]
Hey, thank you for the feedback. :)

For the first point: Yeah, actually this is pretty bad practice to fetch the current time for every value in the map, I've fixed that real quick in 822882b.

To the second point: 
The `retain` method would require the map to be white-locked on every call to `cleanup`, which can cause a lot of unnecessary locks when using the cleanup cycle. Therefore it is first checked using a read lock if there are any keys to be removed at all and after that, if this is the case, the map gets write-locked and the keys are removed. I think this should be more efficient when the map grows larger, but I could do some benchmarks to check that. But feel free to let me know your thoughts on this. :)

**Comment by mattfbacon** [comment]
Yeah it's definitely a compromise because it all depends on the ratio of expired entries to total entries. Now I see it's a lot more nuanced.

That said, I don't know how, but I would like to have a way exposed to either have that method built-in or to be able to do it myself

**Comment by mattfbacon** [comment]
Sorry, fatfingered the close botton
